config/routes.rb
FireHouse::Application.routes.draw do
  resources :fires

  resources :firefighters

  root to: 'welcome#index'

end

app/models/fire.rb
class Fire < ActiveRecord::Base
  attr_accessible :intensity, :location
end

app/models/firefighter.rb
class Firefighter < ActiveRecord::Base
  attr_accessible :age, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/firefighters_controller.rb
class FirefightersController < ApplicationController
  # GET /firefighters
  # GET /firefighters.json
  def index
    @firefighters = Firefighter.all
    expires_in 3.minutes, public: true
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @firefighters }
    end
  end

  # GET /firefighters/1
  # GET /firefighters/1.json
  def show
    @firefighter = Firefighter.find(params[:id])
    expires_in 3.minutes, public: true
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @firefighter }
    end
  end

  # GET /firefighters/new
  # GET /firefighters/new.json
  def new
    @firefighter = Firefighter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @firefighter }
    end
  end

  # GET /firefighters/1/edit
  def edit
    @firefighter = Firefighter.find(params[:id])
  end

  # POST /firefighters
  # POST /firefighters.json
  def create
    @firefighter = Firefighter.new(params[:firefighter])

    respond_to do |format|
      if @firefighter.save
        format.html { redirect_to @firefighter, notice: 'Firefighter was successfully created.' }
        format.json { render json: @firefighter, status: :created, location: @firefighter }
      else
        format.html { render action: "new" }
        format.json { render json: @firefighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /firefighters/1
  # PUT /firefighters/1.json
  def update
    @firefighter = Firefighter.find(params[:id])

    respond_to do |format|
      if @firefighter.update_attributes(params[:firefighter])
        format.html { redirect_to @firefighter, notice: 'Firefighter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @firefighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firefighters/1
  # DELETE /firefighters/1.json
  def destroy
    @firefighter = Firefighter.find(params[:id])
    @firefighter.destroy

    respond_to do |format|
      format.html { redirect_to firefighters_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/fires_controller.rb
class FiresController < ApplicationController
  # GET /fires
  # GET /fires.json
  def index
    @fires = Fire.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fires }
    end
  end

  # GET /fires/1
  # GET /fires/1.json
  def show
    @fire = Fire.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fire }
    end
  end

  # GET /fires/new
  # GET /fires/new.json
  def new
    @fire = Fire.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fire }
    end
  end

  # GET /fires/1/edit
  def edit
    @fire = Fire.find(params[:id])
  end

  # POST /fires
  # POST /fires.json
  def create
    @fire = Fire.new(params[:fire])

    respond_to do |format|
      if @fire.save
        format.html { redirect_to @fire, notice: 'Fire was successfully created.' }
        format.json { render json: @fire, status: :created, location: @fire }
      else
        format.html { render action: "new" }
        format.json { render json: @fire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fires/1
  # PUT /fires/1.json
  def update
    @fire = Fire.find(params[:id])

    respond_to do |format|
      if @fire.update_attributes(params[:fire])
        format.html { redirect_to @fire, notice: 'Fire was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fires/1
  # DELETE /fires/1.json
  def destroy
    @fire = Fire.find(params[:id])
    @fire.destroy

    respond_to do |format|
      format.html { redirect_to fires_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/firefighters_helper.rb
module FirefightersHelper
end

app/helpers/fires_helper.rb
module FiresHelper
end

app/views/firefighters/_form.html.erb
<%= form_for(@firefighter) do |f| %>
  <% if @firefighter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@firefighter.errors.count, "error") %> prohibited this firefighter from being saved:</h2>

      <ul>
      <% @firefighter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/firefighters/edit.html.erb
<h1>Editing firefighter</h1>

<%= render 'form' %>

<%= link_to 'Show', @firefighter %> |
<%= link_to 'Back', firefighters_path %>

app/views/firefighters/index.html.erb
<h1>Listing firefighters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @firefighters.each do |firefighter| %>
  <tr>
    <td><%= firefighter.name %></td>
    <td><%= firefighter.age %></td>
    <td><%= link_to 'Show', firefighter %></td>
    <td><%= link_to 'Edit', edit_firefighter_path(firefighter) %></td>
    <td><%= link_to 'Destroy', firefighter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Firefighter', new_firefighter_path %>

app/views/firefighters/new.html.erb
<h1>New firefighter</h1>

<%= render 'form' %>

<%= link_to 'Back', firefighters_path %>

app/views/firefighters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @firefighter.name %>
</p>

<p>
  <b>Age:</b>
  <%= @firefighter.age %>
</p>


<%= link_to 'Edit', edit_firefighter_path(@firefighter) %> |
<%= link_to 'Back', firefighters_path %>

app/views/fires/_form.html.erb
<%= form_for(@fire) do |f| %>
  <% if @fire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fire.errors.count, "error") %> prohibited this fire from being saved:</h2>

      <ul>
      <% @fire.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :intensity %><br />
    <%= f.number_field :intensity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fires/edit.html.erb
<h1>Editing fire</h1>

<%= render 'form' %>

<%= link_to 'Show', @fire %> |
<%= link_to 'Back', fires_path %>

app/views/fires/index.html.erb
<h1>Listing fires</h1>

<table>
  <tr>
    <th>Location</th>
    <th>Intensity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fires.each do |fire| %>
  <tr>
    <td><%= fire.location %></td>
    <td><%= fire.intensity %></td>
    <td><%= link_to 'Show', fire %></td>
    <td><%= link_to 'Edit', edit_fire_path(fire) %></td>
    <td><%= link_to 'Destroy', fire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fire', new_fire_path %>

app/views/fires/new.html.erb
<h1>New fire</h1>

<%= render 'form' %>

<%= link_to 'Back', fires_path %>

app/views/fires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Location:</b>
  <%= @fire.location %>
</p>

<p>
  <b>Intensity:</b>
  <%= @fire.intensity %>
</p>


<%= link_to 'Edit', edit_fire_path(@fire) %> |
<%= link_to 'Back', fires_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FireHouse</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>What up?</h1>